XeroAPI/xero-netstandard-oauth2-app

.gitignore
README.md
XeroNetStandardApp/Controllers/AssociationsSyncController.cs
XeroNetStandardApp/Controllers/FilesSyncController.cs
XeroNetStandardApp/Controllers/FoldersSyncController.cs
XeroNetStandardApp/Views/AssociationsSync/Create.cshtml
XeroNetStandardApp/Views/AssociationsSync/Index.cshtml
XeroNetStandardApp/Views/AssociationsSync/LoadAssociations.cshtml
XeroNetStandardApp/Views/AssociationsSync/Modify.cshtml
XeroNetStandardApp/Views/FilesSync/Create.cshtml
XeroNetStandardApp/Views/FilesSync/Index.cshtml
XeroNetStandardApp/Views/FilesSync/Modify.cshtml
XeroNetStandardApp/Views/FoldersSync/Create.cshtml
XeroNetStandardApp/Views/FoldersSync/Index.cshtml
XeroNetStandardApp/Views/FoldersSync/Modify.cshtml
XeroNetStandardApp/Views/Shared/Components/SideBar/Default.cshtml
XeroNetStandardApp/Views/Shared/_Layout.cshtml
XeroNetStandardApp/XeroNetStandardApp.csproj

Added:
- AssociationsSyncController
- FilesSyncControlller
- FoldersSyncController
Updated README

Added files API set

---

XeroNetStandardApp/Controllers/ManualJournalInfoController.cs
XeroNetStandardApp/Views/FilesSync/Index.cshtml
XeroNetStandardApp/Views/ManualJournalInfo/Create.cshtml
XeroNetStandardApp/Views/ManualJournalInfo/FindJournal.cshtml
XeroNetStandardApp/Views/ManualJournalInfo/Index.cshtml
XeroNetStandardApp/Views/Shared/Components/SideBar/Default.cshtml

- Create manual journals with tracking categories
- View all manual journals (doesn't show journal lines)
- Show a single manual journal and journal lines
This PR is related to the following [Tracking categories issue](https://github.com/XeroAPI/Xero-NetStandard/issues/350) and verifies that a tracking category can be successfully attached to a manual journal

Add manual journal functionality

---

XeroNetStandardApp/Controllers/ProjectInfoController.cs
XeroNetStandardApp/Views/ProjectInfo/GetTimeEntries.cshtml
XeroNetStandardApp/Views/ProjectInfo/Index.cshtml

Can view time entries and the status of each item.
Used to verify that invoiced statuses do appear in the time entries now (https://github.com/XeroAPI/Xero-NetStandard/issues/355)

Add time entries

---

XeroNetStandardApp/Controllers/AuPayItemInfoController.cs
XeroNetStandardApp/Views/AuPayItemInfo/Index.cshtml
XeroNetStandardApp/Views/Shared/Components/SideBar/Default.cshtml
XeroNetStandardApp/XeroNetStandardApp.csproj

Adds fetching pay item functionality.
Added part of investigation of [issue 437](https://github.com/XeroAPI/Xero-NetStandard/issues/437) to verify if the get call fails when a paid parental leave pay item is created

Adds get pay item controller and view

---

XeroNetStandardApp/Controllers/ManualJournalInfoController.cs
XeroNetStandardApp/Controllers/TaxRateInfoController.cs
XeroNetStandardApp/Views/Shared/Components/SideBar/Default.cshtml
XeroNetStandardApp/Views/TaxRateInfo/Create.cshtml
XeroNetStandardApp/Views/TaxRateInfo/Index.cshtml
XeroNetStandardApp/XeroNetStandardApp.csproj

Adds a new controller with ability to get all tax rates and create a new tax rate

Add tax rate controller

---

XeroNetStandardApp/Controllers/InvoiceSyncController.cs
XeroNetStandardApp/Utilities/TokenUtilities.cs

Invoice Sync Controller Overhaul

---

XeroNetStandardApp/Controllers/InvoiceSyncController.cs
XeroNetStandardApp/Controllers/NzEmployeesInfoController.cs
XeroNetStandardApp/Utilities/TokenUtilities.cs

> ⚠️ Note, this branch is built off the `Invoice Sync Controller Overhaul` PR, therefore, until Invoice Sync Controller Overhaul is merged those changes will appear in this PR as well.
- Added comments and summaries

Overhauled NZ Employees Info Controller

---

XeroNetStandardApp/Controllers/AccountingActivitiesSyncController.cs

- Added comments and summaries

Refactored Accounting Activities Sync Controller

---

XeroNetStandardApp/Controllers/AssetsInfoController.cs

- Added comments and summaries

Refactored Assets controller

---

XeroNetStandardApp/Controllers/AssociationsSyncController.cs

Refactored associations sync controller

---

XeroNetStandardApp/Controllers/AuEmployeesInfoController.cs
XeroNetStandardApp/Controllers/NzEmployeesInfoController.cs
XeroNetStandardApp/XeroNetStandardApp.csproj

Au employees info overhaul

---

XeroNetStandardApp/Controllers/Accounting/BankTransactionsInfoController.cs

Refactored bank transaction controller

---

XeroNetStandardApp/Controllers/Accounting/ContactsInfoController.cs

Refactored contacts info controller

---

XeroNetStandardApp/Controllers/Accounting/OrganisationInfoController.cs

Refactored OrganisationInfo controller

---

XeroNetStandardApp/Controllers/Accounting/PurchaseOrderSyncController.cs

Refactored purchase order sync controller

---

XeroNetStandardApp/Controllers/Accounting/TaxRateInfoController.cs

Refactored TaxRateInfoController

---

XeroNetStandardApp/Controllers/Bankfeed/BankfeedConnectionsController.cs

Refactored Bankfeed Connections Controller

---

XeroNetStandardApp/Controllers/Bankfeed/BankfeedStatementsController.cs

Refactored BankfeedStatements Controller

---

XeroNetStandardApp/Controllers/Files/FilesSyncController.cs

Refactored FilesSync Controller

---

XeroNetStandardApp/Controllers/Files/FoldersSyncController.cs

Refactored FoldersSync Controller

---

XeroNetStandardApp/Controllers/Finance/BankStatementsPlusSyncController.cs

Refactored BankStatementsPlusSync Controller

---

XeroNetStandardApp/Controllers/Finance/CashValidationSyncController.cs

Refactored CashValidationSync Controller

---

XeroNetStandardApp/Controllers/Finance/FinancialStatementsSyncController.cs

Refactored FinancialStatementsSync Controller

---

XeroNetStandardApp/Controllers/Identity/IdentityInfoController.cs

Refactored IdentityInfo Controller

---

XeroNetStandardApp/Controllers/Payroll/AuPayItemInfoController.cs

Refactored AuPayItemInfoController Controller

---

XeroNetStandardApp/Controllers/Accounting/ManualJournalInfoController.cs

Refactored ManualJournalInfo controller

---

XeroNetStandardApp/Controllers/Project/ProjectInfoController.cs

Simple update to match the ProjectAPI controller's token check section with other controller methods.

Just updating project controller to follow others

---

XeroNetStandardApp/Controllers/Accounting/CurrencySyncController.cs
XeroNetStandardApp/Views/CurrencySync/Create.cshtml
XeroNetStandardApp/Views/CurrencySync/Index.cshtml
XeroNetStandardApp/Views/Shared/Components/SideBar/Default.cshtml
XeroNetStandardApp/XeroNetStandardApp.csproj

I've added the get and create currency endpoints to the sample app.

Finalised adding in Currency endpoints

---

XeroNetStandardApp/Controllers/Accounting/InvoiceSyncController.cs
XeroNetStandardApp/Controllers/Accounting/PurchaseOrderSyncController.cs

Reverts XeroAPI/xero-netstandard-oauth2-app#54

Revert "Fix/replace byte by binary - Change byte[] to Binary for Files related APIs"
